disabled_rules:
  - identifier_name
  - trailing_whitespace
  - force_cast
  - force_unwrapping
  - force_try
  - shorthand_operator
  - syntactic_sugar
  - function_parameter_count
  - weak_delegate
  - multiple_closures_with_trailing_closure
  - compiler_protocol_init
  - unused_optional_binding
  - cyclomatic_complexity
  - redundant_string_enum_value
  - switch_case_alignment
  - void_return
  - notification_center_detachment
  - block_based_kvo
  - for_where
  - class_delegate_protocol
  - inert_defer
  
opt_in_rules:
  - vertical_whitespace_opening_braces
  - vertical_whitespace_closing_braces
  - closure_end_indentation
  - closure_spacing

excluded:
  - Pods
  - JSONConverter/Vendor

line_length:
  warning: 600
  error: 900
  ignores_comments: true

file_length:
  warning: 2000
  error: 3000
  
type_name:
 min_length: 4
 max_length:
  warning: 60
  error: 80

type_body_length:
  - 1200
  - 1600

function_body_length:
  warning: 400
  error: 600

large_tuple:
  warning: 6
  error: 8
  
computed_accessors_order:
  order: get_set
  severity: error
  
vertical_whitespace:
  max_empty_lines: 1
  severity: error
  
statement_position:
  statement_mode: default
  severity: error
  
colon:
  flexible_right_spacing: false
  apply_to_dictionaries: true
  severity: error
  
opening_brace:
  severity: error
  
trailing_semicolon: error
comma: error
return_arrow_whitespace: error
no_space_in_method_call: error
mark: error
operator_whitespace: error
closure_parameter_position: error
unused_capture_list: error
unused_closure_parameter: error
trailing_newline: error
control_statement: error
leading_whitespace: error
orphaned_doc_comment: error
unneeded_break_in_switch: error
closure_end_indentation: error
closure_spacing: error
redundant_optional_initialization: error
unused_enumerated: error
duplicate_imports: error
vertical_parameter_alignment: error
comment_spacing: error
